### ISSUE TITLE
v2.0.0-alpha

### ISSUE THREAD

**Issue by benhinchley** [sajari/sajari-sdk-react#86]
**Todo**

**`Input`**
* [x] Fix up key handlers on new `Input` component
  * [x] Right arrow key to select typeahead value
  * [x] ESC key to cancel a query
  * [x] Enter key to override query
  * [x] Fix up input state when backspacing after a query has been made
  _currently the suggestions/typeahead don't appear again_
* [x] `Input` without autocomplete prop should set `q.override`
* [x] Connect `autocomplete` pipeline to input
  * [x] Suggestions and Typeahead
* [x] Allow for the component in the dropdown to be changed
* [ ] Allow for default value to be set
* [ ] Allow for placeholder text

**Results**
* [x] Create `Response` container that blocks rendering if no response

**Theming**
* [x] Connect theming and style overrides into components
  * [ ] Expose component state/props (e.g. isSelected, isDisabled, etc) to override styles
  * [ ] Create HOC component for styling and overrides
  * [ ] Copy class names from current sdk and review #60

**Comment by benhinchley** [comment]
closing in favour of #87
